export const VUE_APP_TOKEN = 'https://zygifx0u41.execute-api.us-west-1.amazonaws.com/tokens'
export const VUE_APP_CARD_DATA = 'https://zygifx0u41.execute-api.us-west-1.amazonaws.com/card-data'
export const _VUE_APP_TOKEN = 'http://localhost:3000/tokens'
export const _VUE_APP_CARD_DATA = 'http://localhost:3000/card-data'
export const VUE_APP_API_TOKEN =  'pk_test_JvbWUqBwgAEAAYgA'
